intenseSite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
	path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from .  import views

app_name = "main"
urlpatterns = [
	path('',views.homepage , name = "homepage"),
	path('about.html' ,views.about , name = "about"),
	path('Enquiry', views.employer, name = "employer"),
	path('Partner', views.partner, name = "partner"),
    path('Contact', views.contact_us, name = "contact"),
    path('log_sign.html',views.log_sign , name= "log_sign"), 
    path("candidate.html", views.candidate, name='candidate'), 
    path("jobs.html", views.jobs, name='jobs'), 
    path("apply.html", views.apply, name='apply'), 
    path("patcomm.html", views.apply, name='patcomm'), 

  
]

main/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
	job_title =  models.CharField(max_length = 100)
	job_des = models.TextField()
	job_sal = models.IntegerField()
	job_loc = models.CharField(max_length = 50)

	def __str__(self):
		return self.job_title

class Contact(models.Model):
	name=models.CharField(max_length=100)
	mail=models.EmailField()
	contactNumber=models.IntegerField()
	message=models.TextField()

	def __str__(self):
		return self.name

class Enquiry(models.Model):
	name=models.CharField(max_length=100)
	contactNumber=models.IntegerField()
	company=models.CharField(max_length=100)
	post=models.CharField(max_length=100)
	city=models.CharField(max_length=100)
	description=models.TextField()

	def __str__(self):
		return self.company

class Partner(models.Model):
	PLACEMENT_AGENCY='PAS'
	FREELANCER='FLS'
	NGO='NGO'
	TRAINING_INSTITUTE='TIS'
	CYBER_CAFE='CCS'
	COLLEGE='CLG'
	TYPES=[
		(PLACEMENT_AGENCY,'PlacementAgency'),
		(FREELANCER,'Freelancer'),
		(NGO,'Ngo'),
		(TRAINING_INSTITUTE,'TrainingInstitute'),
		(CYBER_CAFE,'CyberCafe'),
		(COLLEGE,'College')
	]
	organisationType=models.CharField(max_length=3,choices=TYPES,default="PLACEMENT_AGENCY")
	organisationName=models.CharField(max_length=100)
	name=models.CharField(max_length=100)
	email=models.EmailField()
	contactNumber=models.IntegerField()
	experience=models.IntegerField()

	def __str__(self):
		return self.organisationName

main/forms.py
from django import forms
from .models import Contact
from .models import Enquiry,Partner

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name','mail','contactNumber','message')
        widgets={
                'message':forms.Textarea(attrs={'rows' : 4, 'cols' : 23})
        }

class EnquiryForm(forms.ModelForm):
    class Meta :
        model = Enquiry
        fields = ('name','contactNumber','company','post','city','description')
        widgets={
                'description':forms.Textarea(attrs={'rows' : 4, 'cols' : 23})
        }

class PartnerForm(forms.ModelForm):
    class Meta :
        model = Partner
        fields = ('organisationType','organisationName','name','email','contactNumber','experience')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Job
from .forms import ContactForm,EnquiryForm,PartnerForm


# # Create your views here.
# def base(request):
# 	return render(request = request,
# 				   template_name = 'base.html')
	
def homepage(request):
	return render(request = request,
				  template_name = "home.html",
				  # context = {"jobs" : Job.objects.all}
				  )

def about(request):
	return render(request = request,
		 		  template_name = "about.html",
				  # context = {"jobs" : Job.objects.all}
				  )

def employer(request):

	if request.method=='POST':
		form = EnquiryForm(request.POST)
		if form.is_valid():
			form.save()

	form = EnquiryForm()
	return render(request,'employer.html',{'form':form} )

def partner(request):
	
	if request.method=='POST':
		form = PartnerForm(request.POST)
		if form.is_valid():
			form.save()

	form = PartnerForm()
	return render(request,'partner.html',{'form':form} )



def contact_us(request):

	if request.method=='POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()

	form = ContactForm()
	return render(request,'contact.html',{'form':form} )



def log_sign(request):
	return render(request = request,
				  template_name = "log_sign.html",
				  # context = {"jobs" : Job.objects.all}
				  )	

def candidate(request):
	return render(request = request,
				  template_name = "candidate.html",
				  # context = {"jobs" : Job.objects.all}
				  )


def jobs(request):
	# job1 = Job()
	# job1.job_title = 'Web dev'
	# job1.job_des = 'ABC Education'
	# job1.job_sal = 20000
	# job1.job_loc = 'Delhi'

	# job2 = Job()
	# job2.job_title = 'Devops'
	# job2.job_des = 'ABC Education'
	# job2.job_sal =10000
	# job2.job_loc = 'New Delhi'

	# job3 = Job()
	# job3.job_title = 'Web developer'
	# job3.job_des = 'ABC Education'
	# job3.job_sal = 25000
	# job3.job_loc = 'Banglore'
	
	# job4 = Job()
	# job4.job_title = 'Web developer'
	# job4.job_des = 'ABC Education'
	# job4.job_sal = 25000
	# job4.job_loc = 'Banglore'

	# jobArr = [job1, job2, job3, job4]

	jobArr = Job.objects.all()
	return render(request = request,
				  template_name = "jobs.html",
				  context = {'jobArr' : jobArr}
				  )

def apply(request):
	return render(request = request,
				  template_name = "apply.html",
				  # context = {"jobs" : Job.objects.all}
				  )
def patcomm(request):
	return render(request = request,
				  template_name = "patcomm.html",
				  # context = {"jobs" : Job.objects.all}
				  )

main/templates/about.html
{% load static %}

<!DOCTYPE html>
<head>
  <title>intense placement</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static '/css/styleab.css' %}">
  <link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
  <link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" ></script>
</head>
<body>
<section id="header">
    <div class="menu-bar">
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto" >
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'main:homepage' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="about.html">About Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Enquiry">Employer's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link  " href="Partner">Partner's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="log_sign.html">Login/Signup</a>
                    </li>
                </ul>
            </div>
          </nav>
    </div>
<div class="banner text-center">
    <h1>Welcome to Intense Placement Pvt. Ltd.</h1>
    <h3>Sourcing & Placing Top Talent</h3>
    <h5>A leading placement consultant providing recruitment and man power assistance to clients across segments. Endowed by the experience of our team, we are a leader in international recruitment services, multinational recruiting and career placements.
    </h5>
    <button type="button" class="btn btn-primary "> Join us</button>

    
</div>
</section>

<section class="sec1">
  
    <h1 class="text-center"><b>Why Choose Us</b></h1>
    <div class="card-deck">
        <div class="card  shadow p-3 mb-5 rounded">
          <div class="card-body">
            <h5 class="card-title text-center"><i class="fas fa-cogs"></i> Technical Skills</h5>
            <p class="card-text">Our bespoke recruiting solutions use the right mix of technology and human intelligence to help you attract and hire candidates who contribute to both your business goals and culture</p>
          </div>
        </div>
        <div class="card  shadow p-3 mb-5 rounded">
         <div class="card-body">
            <h5 class="card-title text-center"><i class="fas fa-user-tie"></i> Professional Services</h5>
            <p class="card-text">We believe in people. We believe in harnessing the human potential to build stellar careers.One of the largest recruitment agencies in the world, we help nurture the ambitions of millions across the world</p>
          </div>
        </div>
        <div class="card  shadow p-3 mb-5 rounded">
          <div class="card-body">
            <h5 class="card-title text-center"><i class="fas fa-phone"></i> Great Support</h5>
            <p class="card-text">We offer temporary and permanent workforce solutions to a large client base spread across industries. Choose us for exceptional consultancy services designed for business growth and operational excellence.</p>
          </div>
        </div>
      </div>
</section>
<section class="sec2">
    <h2 class="text-center"><b>What We Do</b></h2>
    
		
	<div class="card-deck">
		<div class="card shadow p-3 mb-5" style="height:14rem;">
			<i class=" card-img-top fas fa-list-alt fa-5x"></i>
		  <div class="card-body">
			<h5 class="card-title text-center ">We offer a premium selection of jobs across sectors and levels</h5>
		  </div>
		</div>
		<div class="card shadow p-3 mb-5" style="height:14rem;">
			<i class=" card-img-top fas fa-search fa-5x"></i>
		  <div class="card-body">
			<h5 class="card-title text-center ">We help you to find your dream assignment today</h5>
		  </div>
		</div>
		<div class="card shadow p-3 mb-5" style="height:14rem;">
			<i class=" card-img-top fas fa-trophy fa-5x"></i>
		  <div class="card-body">
			<h5 class="card-title text-center">We build assets that help organizations scale new heights</h5>
		  </div>
		</div>
      </div>	
      
	
</section>

<section class="sec3">
  <h2 class="text-center"><b>Our Industries of Expertise</b></h2>
    <h5 class="text-center">Excellence and Success</h5>

    <div class="card-deck">
		<div class="card shadow p-3 mb-5 ">
      <i class="fas fa-tasks fa-5x"></i>
      		  <div class="card-body">
			<h5 class="card-title">Recruitment Process Outsourcing</h5>
			<p class="card-text">We act as an extended arm of our clients and help manage their end to end recruitment needs</p>
		</div>
		</div>
		<div class="card shadow p-3 mb-5">
		  <i class="fas fa-arrow-alt-circle-up fa-5x"></i>
		  <div class="card-body">
			<h5 class="card-title">Career Transition Services</h5>
			<p class="card-text">Comprehensive outplacement services based on unique needs of client</p>
		  </div>
		</div>
		<div class="card shadow p-3 mb-5">
      <i class="fas fa-stamp fa-5x"></i>		  
      <div class="card-body">
			<h5 class="card-title">Executive Search</h5>
			<p class="card-text">Exclusive and retained our Executive Search Practice is focused on Board and CXO level leadership Hiring</p>
		  </div>
		</div>
	  </div>
</section>
<footer class="foot" >
  follow us on 
  <i class="fab fa-instagram"></i>
  <i class="fab fa-facebook-square"></i>
  <i class="fab fa-linkedin"></i>
  <i class="fab fa-twitter-square"></i>
   
    </footer>
</body>
</html>

main/templates/apply.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>intense placement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styleapply.css' %}">
<link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
<script src="{% static 'styles/bootstrap-4.5.0/js/bootstrap.min.js' %}" ></script>
</head>
<body>
<section id="header">
    <div class="menu-bar">
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto" >
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'main:homepage' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="about.html">About Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Enquiry">Employer's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link  " href="Partner">Partner's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="log_sign.html">Login/Signup</a>
                    </li>
                </ul>
            </div>
          </nav>
    </div>
    
<div class="banner">
  <div >
    <h1 class=" hh text-center" >APPLICATION ZONE</h1>
    </div>
    
      
		<div class=" appform">
				<form action="#" id ="aly"class="needs-validation">
					<div class="form-group ">
						<input type="text" class="form-control" id="name" placeholder="Name" name="name" required>
					</div>
					<div class="form-group">
						<input type="email" class="form-control" id="email" placeholder="Email" name="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
					</div>
					<div class="form-group">
						<input type="phone" class="form-control" id="contact" placeholder="Contact Number(123-456-7890)" name="contact" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"required>
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="city" placeholder="Current City" name="city" required>
					</div>
					<div class="form-group">
					<span class="text-white"> Upload Resume :
						<input type="file" class="form-control" id="resume" placeholder="Upload Resume" name="resume" required></span>
					</div>
					<button type="submit" style="float:right" class="btn btn-primary text-white">Submit</button>
				</form>
		</div>
		

</section>
    
    

<footer class="foot" >
  follow us on 
  <i class="fab fa-instagram"></i>
  <i class="fab fa-facebook-square"></i>
  <i class="fab fa-linkedin"></i>
  <i class="fab fa-twitter-square"></i>
   
    </footer>
</body>
</html>

main/templates/candidate.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>intense placement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/stylecan.css' %}">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link href="fontawesome-free-5.13.0-web/css/fontawesome.css" rel="stylesheet">
  <link href="fontawesome-free-5.13.0-web/css/brands.css" rel="stylesheet">
  <link href="fontawesome-free-5.13.0-web/css/solid.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" ></script> -->
<link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
<script src="{% static 'styles/bootstrap-4.5.0/js/bootstrap.min.js' %}" ></script>
</head>
<body>
<section id="header">
    <div class="menu-bar">
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto" >
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'main:homepage' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="about.html">About Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Enquiry">Employer's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link  " href="Partner">Partner's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="log_sign.html">Login/Signup</a>
                    </li>
                </ul>
            </div>
          </nav>
    </div>
<div class="banner text-center">
    <div class="row">
    		<div class=" canform col-4">
      <form action="#" class="needs-validation ">
        <div class="form-group">
          <input type="text" class="form-control" id="name" placeholder="Full Name" name="name" required>
        </div>
        <div class="form-group">
          <input type="email" class="form-control" id="email" placeholder="Email" name="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
        </div>
        <div class="form-group">
          <input type="tel" class="form-control" id="contact" placeholder="Contact Number(123-456-7890)" name="contact" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="fname" placeholder="Father Name" name="fname" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="edu" placeholder="Education" name="edu" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="pn" placeholder="PAN Number" name="pn" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="an" placeholder="Aadhar Number" name="an" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="location" placeholder="Location" name="location" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="sal" placeholder="Last Salary" name="sal" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="comp" placeholder="Last Company" name="comp" required>
        </div>
        <div class="form-group">
          <span class="text-white">Upload Resume:
          <input type="file" class="form-control" id="resume" placeholder="Upload Resume" name="resume" required>
        </span>
        </div>
        <button type="submit" style="float:right" class="btn btn-primary text-white">Submit </button>
      </form>
  </div>
  <div class=" col-6"><h1 class="text-white">Welcome To Our Candidate Zone</h1></div>

</div>
</section>
    
    

<footer class="foot" >
  follow us on 
  <i class="fab fa-instagram"></i>
  <i class="fab fa-facebook-square"></i>
  <i class="fab fa-linkedin"></i>
  <i class="fab fa-twitter-square"></i>
   
    </footer>
</body>
</html>

main/templates/contact.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<head>
    <title>intense placement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/stylecon.css' %}">
<link rel="stylesheet" href="{% static 'styles/bootstrap-4.5.0/css/bootstrap.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/fontawesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/brands.css' %}" rel="stylesheet">
<link href="{% static 'plugins/fontawesome-free-5.13.0-web/css/solid.css' %}" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
<script src="{% static 'styles/bootstrap-4.5.0/js/bootstrap.min.js' %}" ></script>
</head>
<body>
<section id="header">
    <div class="menu-bar">
        <nav class="navbar navbar-expand-lg navbar-light ">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto" >
                    <li class="nav-item ">
                        <a class="nav-link " href="{% url 'main:homepage' %}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="about.html">About Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Enquiry">Employer's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link  " href="Partner">Partner's Zone</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="log_sign.html">Login/Signup</a>
                    </li>
                </ul>
            </div>
          </nav>
    </div>
<div class="banner">
    <h1 class="text-center">Contact Us</h1>
    
</div>
</section>
<section class="banner2">
<div class="card-deck">
    <div class="card">
        <i class="fas fa-envelope fa-3x"></i>
        <div class="card-body">
            <p class="card-text"><a href="#">hr@intenseplacement.com</a> <br>
                <a href="#" >manager@intenseplacement.com</a>
            </p>
        </div>
    </div>
    <div class="card ">
        <i class="fas fa-phone fa-3x"></i>
        <div class="card-body">
            <p class="card-text "><a href="#">7011-036-020</a>
            </p>
        </div>
    </div>
    <div class="card ">
        <i class="fas fa-map-marker-alt fa-3x"></i>
        <div class="card-body">
            <p class="card-text "><a href="#">H-55/A , Shiv Ram Park , Nangloi , New Delhi-41</a>
            </p>
        </div>
    </div>
</div>
</section>
<section class="sec2">
<div class="row">
    <div class="col-1"></div>
<div   class="col-4" >
    <form method="POST">
        {%csrf_token%}
        <table>
            <tr colspan=2>
                {{form | crispy}}
                <button type="submit"   class="btn btn-primary text-white">Submit</button>
            </tr>
        </table>
    <!--<form class=" cont">
        <div class="form-group">
            <input type="text" class="form-control" id="name" placeholder="Enter your Name" name="name">
        </div>
        <div class="form-group">
            <input type="email" class="form-control" name="email" id="email" placeholder="Enter your email">
        </div>
        <div class="form-group">
            <input type="phone" class="form-control" name="phone" id="phone" placeholder="Enter your phone">
        </div>
        <div class="form-group">
            <textarea name="message" class="form-control" id="message" cols="10" rows="5" placeholder="Enter your Message"></textarea>
        </div>
            </form>-->
    </form>
</div>

<div class="col-5 ml-4">
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14002.988820098652!2d77.0573458!3d28.667287!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x95df2576821c9451!2sIntense%20Placement%20Pvt.%20Ltd.!5e0!3m2!1sen!2sin!4v1589795151848!5m2!1sen!2sin" width="600" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
</div>  
</section>  

<footer class="foot" >
  follow us on 
  <i class="fab fa-instagram"></i>
  <i class="fab fa-facebook-square"></i>
  <i class="fab fa-linkedin"></i>
  <i class="fab fa-twitter-square"></i>
   
    </footer>
</body>
</html>